---
- name: reset kubernetes master node
  hosts: master
  gather_facts: yes
  ignore_errors: yes
  vars:
    cni: "{{ cni }}"
  tasks:
    - name: drain master node
      shell: kubectl drain {{ ansible_hostname }} --delete-local-data --force --ignore-daemonsets
    - name: delete worker nodes
      shell: kubectl delete nodes --all
    - name: reset master node
      shell: kubeadm reset -f & rm /etc/cni/net.d/* & rm /home/pi/.kube/config
      become_user: root

- name: reset all worker nodes
  hosts: all
  become: yes
  become_user: root
  ignore_errors: yes
  gather_facts: no
  tasks:
    - name: reset worker
      shell: kubeadm reset -f
    - name: clear weave
      shell: weave reset --force & ip link delete weave & rm /opt/cni/bin/weave-*
      when: cni == "weave"
    - name: clear calico
      shell: ip link delete calico & rm /opt/cni/bin/calico* & modprobe -r ipip
      when: cni == "calico"
    - name: clear cilium
      shell: ip link delete cilium_vxlan & ip link delete cilium_net & rm /opt/cni/bin/cilium*
      when: cni == "cilium"
    - name: clear flannel
      shell: ip link delete cni0 & ip link delete flannel.1
      when: cni == "flannel"
    - name: resart kubelet
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet