---
- name: create kubernetes cluster
  hosts: master
  become: yes
  become_user: root
  gather_facts: no
  vars:
    cni: "{{ cni }}"
  tasks:
    - name: turn off swap
      shell: swapoff -a
    - name: generate token
      shell: kubeadm token generate
      register: token

    - name: create cluster with flannel cni
      shell: kubeadm init --token={{ token.stdout }} --pod-network-cidr=10.244.0.0/16
      when: cni == "flannel"
    - name: create cluster with calico cni
      shell: kubeadm init --token={{ token.stdout }} --pod-network-cidr=192.168.0.0/16
      when: cni == "calico"
    - name: create cluster with cilium cni
      shell: kubeadm init --token={{ token.stdout }} --pod-network-cidr=10.217.0.0/16
      when: cni == "cilium"
    - name: create cluster with weavenet cni
      shell: kubeadm init
      when: cni == "weavenet"
    
    - name: generate kube config
      shell: mkdir -p /home/pi/.kube && sudo cp -i /etc/kubernetes/admin.conf /home/pi/.kube/config && sudo chown $(id -u):$(id -g) /home/pi/.kube/config
      become_user: pi

    - name: install network plugin
      shell: curl -sSL https://rawgit.com/coreos/flannel/master/Documentation/kube-flannel.yml | sed "s/amd64/arm/g" | kubectl create -f -
      become_user: pi