---
- name: obtain join command
  hosts: master
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - shell: kubeadm token create --print-join-command
      register: join_cmd
    - add_host:
        name: "K8S_JOIN_CMD"
        token: "{{ join_cmd.stdout }}"

- name: worker nodes join the cluster
  hosts: workers
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: turn off swap
      shell: swapoff -a
    - name: let worker nodes join the cluster
      shell: "{{ hostvars['K8S_JOIN_CMD']['token'] }}"