---
- name: worker nodes join the cluster
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: turn off swap
      shell: swapoff -a
    - name: obtain work nodes join token
      shell: kubeadm token create --print-join-command
      register: join_cmd
      delegate_to: master
    - name: let worker nodes join the cluster
      shell: {{ join_cmd.stdout }}
      delegate_to: workers