---
- name: install K8sDDS dependencies
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks: 
    - include: optimize_os.yml
    - include: install_docker.yml
    - include: install_k8s.yml
